# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Brews (Packages)
brew "ack"
brew "autojump"
brew "bat"
brew "exa"
brew "broot"
brew "fasd"
brew "fd"
brew "fzf"
brew "gcc"
brew "grip"
brew "httpie"
brew "minimal-racket"
brew "neovim"
brew "nnn"
brew "ranger"
brew "rcm"
brew "ripgrep"
brew "roswell"
brew "rustup-init"
brew "shellcheck"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "xclip"

# Casks (Applications)
cask "alfred"
cask "dropbox"
cask "db-browser-for-sqlite"
cask "google-chrome"
cask "skim"
cask "visual-studio-code"
